apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
    eventing.knative.dev/source: "true"
    knative.dev/crd-install: "true"
  name: kafkasources.sources.eventing.knative.dev
spec:
  group: sources.eventing.knative.dev
  names:
    categories:
    - all
    - knative
    - eventing
    - sources
    kind: KafkaSource
    plural: kafkasources
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            bootstrapServers:
              type: string
            consumerGroup:
              type: string
            net:
              properties:
                sasl:
                  properties:
                    enable:
                      type: boolean
                    password:
                      type: string
                    user:
                      type: string
                  type: object
                tls:
                  properties:
                    cert:
                      type: string
                    enable:
                      type: boolean
                    key:
                      type: string
                  type: object
              type: object
            serviceAccountName:
              type: string
            sink:
              type: object
            topics:
              type: string
          required:
          - bootstrapServers
          - topics
          - consumerGroup
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  severity:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            observedGeneration:
              format: int64
              type: integer
            sinkUri:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
